### PR TITLE
Add basic theme support via ttkthemes

### PR DESCRIPTION
**Pull request by MCOfficer**
- Adds a `requirements.txt` file for pypi packages

- Changes the main `Tk` object to a `ThemedTk`, a drop-in replacement that supports themeing

- Changes `PopupWindow` to use `tkinter.ttk` widgets rather than their `tkinter` counterparts

- Uses `arc` as default theme, for a list of available themes see http://ttkthemes.readthedocs.io/en/latest/themes.html

- Changes the CI builds to work with ttkthemes (my test build [here](https://ci.appveyor.com/project/MCOfficer/endless-sky-mission-builder/builds/25619480) failed because i revoked appveyor's repo access so it cannot deploy, but the build itself went through)

- Changes the CI builds on linux to install the `chrpath` package, since nuitka occasionally needs it

---

Before / After on Windows 10 with dark theme:
grafik

Before / After on Ubuntu Mate, default theme:
grafik

### CODE REVIEW

**Comment by shitwolfymakes** [comment]
I like this a lot, but we'll have to table this until I've finished reworking the GUI. Once that's done I'll let you know and you can run this against the updated `indev` branch

**Comment by MCOfficer** [comment]
the change to the code itself is literally 7 characters, so it shouldn't be hard to adapt to GUI changes. You can bench this as long as necessary.

**Comment by shitwolfymakes** [comment]
I get that, I'm just not sure how it will interact with the custom widgets I created. Unless you're already using the new widgets?

**Comment by MCOfficer** [comment]
i have not been following the latest developments, but as long as your custom widgets extend ttk widgets (and don't mess with fundamental drawing stuff, i guess), they should be themeable. i tested this on the indev branch (see the screenshots), and while there are some rough edges (e.g. the popup window being unthemed), i didn't notice anything break.

**Review by shitwolfymakes — COMMENTED** [review]
Please make sure all objects that are ttk are declared via ttk.*. I'd like to keep this in particular uniform throughout the code. Thanks!

**Comment by shitwolfymakes** [comment]
`from ttkthemes import ThemedTk` needs to be declared in guiutils.py, between `from tkinter import ttk`, and `from functools import partial`

**Comment by MCOfficer** [comment]
> 
> 
> `from ttkthemes import ThemedTk` needs to be declared in guiutils.py, between `from tkinter import ttk`, and `from functools import partial`

there is no occurence of Tk or ThemedTk in guiutils.py, only in GUI.py, where it is properly imported

**Comment by shitwolfymakes** [comment]
Oh, that import has to go wherever the instance is declared?

**Comment by MCOfficer** [comment]
> 
> 
> Oh, that import has to go wherever the instance is declared?

it goes wherever you use it, yes

**Pull request merged**
