### PR TITLE
Migrate CI to Github Actions

### PR DESCRIPTION
**Pull request by MCOfficer**
**Feature:** This PR implements the feature request detailed and discussed in issue #21

## Feature Details
This PR migrates the current CI to Github Actions.
It builds binaries and packaged executables for
- [x] Windows
- [x] Linux
- [ ] MacOS

Builds are triggered by new releases and pushes to `master` and `indev`. In the case of releases, [artifacts are uploaded as release assets](https://github.com/MCOfficer/Endless-Sky-Mission-Builder/releases/tag/test4). In either case, artifacts can be [downloaded from the workflow run](https://github.com/MCOfficer/Endless-Sky-Mission-Builder/actions/runs/114593073).

### CODE REVIEW

**Comment by MCOfficer** [comment]
@shitwolfymakes i need you to check wether any of the artifacts from the [latest build](https://github.com/MCOfficer/Endless-Sky-Mission-Builder/actions/runs/114879790) are any good. with some luck, that's macos support done.

PS: according to the docs, they shouldn't have an icon yet, but it's simple to change that.

**Comment by shitwolfymakes** [comment]
@MCOfficer The build works, but it crashes on launch.

Stack trace:
```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/Users/wolfy/Desktop/artifact/dist/ESMB.app/Contents/MacOS/tcl" not found.
[3565] Failed to execute script pyi_rth__tkinter
```

**Comment by MCOfficer** [comment]
@shitwolfymakes can you [this](https://github.com/MCOfficer/Endless-Sky-Mission-Builder/actions/runs/118228443)?

ref https://github.com/pyinstaller/pyinstaller/issues/1350#issuecomment-445515792

**Comment by shitwolfymakes** [comment]
Whatever you did fixed the missing tcl libraries, but there is a new error(when running all the executables)

Stack trace:
```
Traceback (most recent call last):
  File "src/ESMB.py", line 24, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "src/__init__.py", line 9, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "src/ESMB.py", line 24, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "src/model/__init__.py", line 18, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "src/model/file_data_parsers/__init__.py", line 12, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "src/model/file_data_parsers/FilePhraseItemParser.py", line 17, in <module>
ModuleNotFoundError: No module named 'model'
```

**Comment by shitwolfymakes** [comment]
Closing this, as it is superseded by #27, and the work being done in the [`cicd-buildout`](https://github.com/shitwolfymakes/Endless-Sky-Mission-Builder/tree/cicd-buildout) branch

**Pull request closed without merging**
